services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 127.0.0.1:6379:6379
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: balancer
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balancer
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql/:ro